2.4 - Parser’s first steps: parsing let statements: PASS
If we now change our test case input of TestLetStatements from this

    input := `
let x = 5;
let y = 10;
let foobar = 838383;
`
to this invalid input where tokens are missing

    input := `
let x 5;
let = 10;
let 838383;
`

$ go test -v ./parser

=== RUN   TestLetStatements
    parser_test.go:75: parser has 3 errors
    parser_test.go:77: parser error: "expected next token to be =, got INT instead"
    parser_test.go:77: parser error: "expected next token to be IDENT, got = instead"
    parser_test.go:77: parser error: "expected next token to be IDENT, got INT instead"
--- FAIL: TestLetStatements (0.00s)
FAIL
FAIL	github.com/unknowntpo/monkey/parser	0.005s
FAIL